### ISSUE TITLE
train相关问题

### ISSUE THREAD

**Issue by qiujianchen** [GuoQuanhao/yolov5-Paddle#13]
作者您好，我在使用您的数据集训练YOLOv5n模型时，出现一个警告：
Epoch   gpu_mem       box       obj       cls    labels  img_size
      1/99     1.94G   0.09787    0.5162         0       679       640: 100%|███████████████████████████████████████████████████████████████████████| 57/57 [04:48<00:00,  5.05s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:  25%|██████████████▎                                          | 1/4 [00:17<00:53, 17.96s/it]/mnt/YOLOv5-Paddle-main/utils/loss.py:191: RuntimeWarning: divide by zero encountered in true_divide
  j = np.maximum(r, 1 / r).max(2) < self.hyp['anchor_t']  # compare 
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|█████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.56s/it]
                 all         50       7742      0.571      0.664      0.579      0.188

训练集为450，验证集为50，训练的目标只有一类“钢筋” （label: rebar）
想问一下会影响后续的部署使用吗？

**Comment by GuoQuanhao** [comment]
不会的。本次更新实现了yolov5的全新迁移，能够实现分类、分割、检测和各种格式模型的导出。
