### ISSUE TITLE
训练的有问题

### ISSUE THREAD

**Issue by Shengshenlan** [GuoQuanhao/YOLOv5-Paddle#17]
Traceback (most recent call last):
  File "train.py", line 641, in <module>
    main(opt)
  File "train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 311, in train
    loss, loss_items = compute_loss(pred, targets)  # loss scaled by batch_size
  File "/home/aistudio/yolov5-Paddle-main/utils/loss.py", line 124, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/home/aistudio/yolov5-Paddle-main/utils/loss.py", line 181, in build_targets
    ai = paddle.arange(na, dtype=paddle.float32).reshape([na, 1]).tile([1, nt])  # same as .repeat_interleave(nt)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 3147, in tile
    return _C_ops.tile(x, repeat_times)
ValueError: (InvalidArgument) Every element of the input 'repeat_times' for tile op must be greater than 0, but the value given is 0.
  [Hint: Expected repeat_times_data[i] > 0, but received repeat_times_data[i]:0 <= 0:0.] (at /paddle/paddle/phi/infermeta/unary.cc:3743)
以上是错误信息

  0                -1  1      1792  models.common.Conv                      [3, 16, 6, 2, 2]              
  1                -1  1      4736  models.common.Conv                      [16, 32, 3, 2]                
  2                -1  1     11664  models.common.C3_Faster                 [32, 32, 1]                   
  3                -1  1     18688  models.common.Conv                      [32, 64, 3, 2]                
  4                -1  2    149120  models.common.C3_Faster                 [64, 64, 2]                   
  5                -1  1     74240  models.common.Conv                      [64, 128, 3, 2]               
  6                -1  3   1662720  models.common.C3_Faster                 [128, 128, 3]                 
  7                -1  1    295936  models.common.Conv                      [128, 256, 3, 2]              
  8                -1  1   4402176  models.common.C3_Faster                 [256, 256, 1]                 
  9                -1  1    165376  models.common.SPPF                      [256, 256, 5]                 
 10                -1  1     33280  models.common.Conv                      [256, 128, 1, 1]              
 11                -1  1         0  paddle.nn.layer.common.Upsample         [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1     91648  models.common.C3                        [256, 128, 1, False]          
 14                -1  1      8448  models.common.Conv                      [128, 64, 1, 1]               
 15                -1  1         0  paddle.nn.layer.common.Upsample         [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     23296  models.common.C3                        [128, 64, 1, False]           
 18                -1  1     37120  models.common.Conv                      [64, 64, 3, 2]                
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1     75264  models.common.C3                        [128, 128, 1, False]          
 21                -1  1    147968  models.common.Conv                      [128, 128, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1    297984  models.common.C3                        [256, 256, 1, False]          
 24      [17, 20, 23]  1     23001  models.yolo.Detect                      [12, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [64, 128, 256]]
YOLOv5n-Faster summary: 220 layers, 7524457 parameters, 7454601 gradients, 14.0 GFLOPs
以上是我的模型

**Comment by GuoQuanhao** [comment]
你的yaml文件是啥

**Comment by Shengshenlan** [comment]
# YOLOv5 Reproduction 🚀 by GuoQuanhao, GPL-3.0 license

# Parameters
nc: 12  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3_Faster, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3_Faster, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3_Faster, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3_Faster, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
自己改的一个模块C3_Faster
yolov5n-Faster.yaml

**Comment by GuoQuanhao** [comment]
C3_Faster模块咋写的呢

**Comment by Shengshenlan** [comment]
```python

def drop_path(x, drop_prob=0.0, training=False):
    """
    Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ...
    """
    if drop_prob == 0.0 or not training:
        return x
    keep_prob = paddle.to_tensor(1 - drop_prob)
    shape = (paddle.shape(x)[0],) + (1,) * (x.ndim - 1)
    random_tensor = keep_prob + paddle.rand(shape, dtype=x.dtype)
    random_tensor = paddle.floor(random_tensor)  # binarize
    output = x.divide(keep_prob) * random_tensor
    return output


class DropPath(nn.Layer):
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)

class PConv(nn.Layer):
    def __init__(self, dim, kernel_size=3, n_div=4):
        super().__init__()

        self.dim_conv = dim // n_div
        self.dim_untouched = dim - self.dim_conv

        self.conv = nn.Conv2D(self.dim_conv, self.dim_conv, kernel_size, padding=(kernel_size - 1) // 2,
                              bias_attr=False)

    def forward(self, x):
        x1, x2 = paddle.split(x, [self.dim_conv, self.dim_untouched], axis=1)
        x1 = self.conv(x1)
        x = paddle.concat([x1, x2], axis=1)

        return x

class Faster_Block(nn.Layer):
    def __init__(self, dim, expand_ratio=2, act_layer=nn.ReLU, drop_path_rate=0.0):
        super().__init__()

        self.pconv = PConv(dim)

        self.conv1 = nn.Conv2D(dim, dim * expand_ratio, 1, bias_attr=False)

        self.bn = nn.BatchNorm2D(dim * expand_ratio)
        self.act_layer = act_layer()

        self.conv2 = nn.Conv2D(dim * expand_ratio, dim, 1, bias_attr=False)

        self.drop_path = DropPath(drop_path_rate) if drop_path_rate > 0.0 else nn.Identity()

    def forward(self, x):
        residual = x

        x = self.pconv(x)
        x = self.conv1(x)
        x = self.bn(x)
        x = self.act_layer(x)
        x = self.conv2(x)

        x = residual + self.drop_path(x)
        return x

class C3_Faster(C3):
    # C3 module with cross-convolutions
    def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5):
        super().__init__(c1, c2, n, shortcut, g, e)
        c_ = int(c2 * e)
        self.m = nn.Sequential(*(Faster_Block(c_, c_) for _ in range(n)))
```

**Comment by Shengshenlan** [comment]
Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
    107/299       2.2G    0.05337    0.04626    0.02203          1        640: 1
Traceback (most recent call last):
  File "train.py", line 641, in <module>
    main(opt)
  File "train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 343, in train
    lr = [x['learning_rate'] for x in optimizer._param_groups]  # for loggers
  File "train.py", line 343, in <listcomp>
    lr = [x['learning_rate'] for x in optimizer._param_groups]  # for loggers
KeyError: 'learning_rate'
每次训练到107轮都会有这个错误是为啥捏

**Comment by GuoQuanhao** [comment]
现在训练是没问题了吗？你可以print出optimizer._param_groups中的参数，我目前没有遇到这个问题
