### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by BUAADreamer** [GuoQuanhao/yolov5-Paddle#2]
![image](https://user-images.githubusercontent.com/64362896/147360791-6b3eb791-34f0-4022-9e35-442cc0f1a90c.png)
问一下这个可能是啥原因，谢谢了
我的数据集格式已经整理成了百分比格式的0 x1 y1 w h但是还是报了这个错
我正在训练一个和光栅数据集类似的数据集

**Comment by BUAADreamer** [comment]
已解决，是因为第一次格式错误的时候保存了cache但是第二次没有把cache删掉，一直用的最开始的数据

**Comment by GuoQuanhao** [comment]
好的，问题解决我将关闭这个issue

**Comment by GuoQuanhao** [comment]
本次实现了yolov5的全新迁移，能够实现分类、分割、检测和各种格式模型的导出
