### ISSUE TITLE
多卡训练

### ISSUE THREAD

**Issue by thunder95** [GuoQuanhao/yolov5-Paddle#3]
浩佬有多卡训练的脚本么， 虽然python -m paddle.distributed.launch train.py也能跑，但是打印日志这些有问题

**Comment by GuoQuanhao** [comment]
多卡还没写哦，最近忙着找实习，估计代码更新得延期一会儿

**Comment by GuoQuanhao** [comment]
本次更新实现了yolov5的全新迁移，能够实现分类、分割、检测和各种格式模型的导出。现在已支持多卡了，以及任意指定单卡
