### ISSUE TITLE
gradients减少

### ISSUE THREAD

**Issue by BhAem** [GuoQuanhao/yolov5-Paddle#5]
![image](https://user-images.githubusercontent.com/69887620/152993470-cdbaf824-1ff0-4d46-ad9b-dcc54ab6505e.png)

为什么进行检测时会出现参数和gradients减少？

**Comment by GuoQuanhao** [comment]
YOLOv5使用thop包计算的，Paddle这部分是我自己写的，感谢指出，应该是统计部分存在bug，我mark一下哈

**Comment by GuoQuanhao** [comment]
本次实现了yolov5的全新迁移，能够实现分类、分割、检测和各种格式模型的导出
