### ISSUE TITLE
数据集验证时间过长

### ISSUE THREAD

**Issue by KevinXinA** [GuoQuanhao/yolov5-Paddle#7]
请问下怎么导致训练数据集时需要30秒，验证时却需要3分钟？

**Comment by KevinXinA** [comment]
前十轮有这个现象，后面正常，我是win10

**Comment by KevinXinA** [comment]
> Paddle的Tensor限制，验证采用的numpy，由于训练前期，模型训练精度还不高，导致产生大量的框，因此拉满了速度。目前这个仓库的完备性不够高，等我有空了会重整所有代码

好的谢谢

**Comment by GuoQuanhao** [comment]
本次采用最新的paddlepaddle更新实现了yolov5的全新迁移，能够实现分类、分割、检测和各种格式模型的导出。现在应该不存在这个问题了
