### ISSUE TITLE
继续训练

### ISSUE THREAD

**Issue by C1078617739** [GuoQuanhao/yolov5-Paddle#9]
继续训练时遇到train代码346行，learning_rate keyerror的问题，我尝试过修改代码，但都报错，请教一下可能是什么问题

**Comment by C1078617739** [comment]
在aistudio中，停止训练后继续训练，继续训练了一个epoch后（并未到验证阶段），就出现这个问题

**Comment by diaoa1900** [comment]
> 继续训练时遇到train代码346行，learning_rate keyerror的问题，我尝试过修改代码，但都报错，请教一下可能是什么问题

paddle中，optimizer._param_groups（它是由字典组成的list）中的每个元素均默认没有learning_rate属性，这个learning_rate在Warmup时进行创建并赋值。当你停止训练后再训练的时候Warmup已经结束了没有再运行Warmup相关代码，learning_rate键值对不存在，所以会报错。

如果你只是想让它继续正常运行，可以将train.py中第346行的`x['learning_rate']`改为任意的一个值，它只是为了写入`results.csv`文件中，值无所谓

如果你想保持和 ultralytics/yolov5 仓库中 v6.0版本的学习率结果一致，可以将train.py的第346行改成
当Warmup未结束时，将lr赋值为`[x['learning_rate'] for x in optimizer._param_groups]`；
当Warmup结束后，将lr赋值为`[optimizer.get_lr() for x in optimizer._param_groups]`。

这个paddle版本的resume和  ultralytics/yolov5  对比好像还存在的一个问题是 **每次resume后前几个epoch的precision和recall、mAP都会比上次停止时的值低，需要训练几个epoch才能回到上次的精度**

**Comment by C1078617739** [comment]
> 

学习了，谢谢
